max_width = 80

reorder_imports = true
reorder_modules = false
use_small_heuristics = "Max"

fn_call_width   = 60
chain_width     = 60

unstable_features   = true
space_after_colon   = true
indent_style        = "block"
binop_separator     = "Front"
comment_width       = 80
normalize_comments  = false
wrap_comments       = true

