---

name: CI
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: auto

jobs:
  test:
    name: Test
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
        toolchain: [stable, nightly]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test --no-fail-fast
      - uses: actions-rs/cargo@v1
        with:
          command: check --release

